version: '3.8'

services:
  patient-db:
    image: postgres:latest
    container_name: patient-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "500:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - patient-net

  auth-service-db:
    image: postgres:latest
    container_name: auth-service-db
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5001:5432"  # Exposes to host on 5001, internal is still 5432
    volumes:
      - ./auth-postgres:/docker-entrypoint-initdb.d
    networks:
      - patient-net

  billingservice:
    build:
      context: ../billingservice      # 👈 Adjust path to your billing service folder
    container_name: billingservice
#    ports:
#      - "9001:9001"
    networks:
      - patient-net

  kafka:
     image: bitnami/kafka:latest
     container_name: kafka
     environment:
       - KAFKA_KRAFT_MODE=true
       - KAFKA_CFG_NODE_ID=0
       - KAFKA_CFG_PROCESS_ROLES=controller,broker
       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#     ports:
#       - "9092:9092"
     networks:
       - patient-net

  analyticsservice:
    build:
      context: ../analyticsservice
    container_name: analytics-service
#    ports:
#      - "8095:8095"
    depends_on:
      - kafka
    networks:
      - patient-net

  patient-app:
    build:
      context: ../demo
    container_name: patient-app
    depends_on:
      - patient-db
      - billingservice
    networks:
      patient-net:
        aliases:
          - patient-service

  api-gateway:
    build:
      context: ../apigatewayservice
    container_name: api-gateway
    ports:
      - "4004:4004"
    depends_on:
      - patient-app
    networks:
      - patient-net

  auth-service:
    build:
      context: ../authservice
    container_name: auth-service
    ports:
      - "9006:9006"
    depends_on:
      - auth-service-db
    networks:
      - patient-net

networks:
  patient-net:
    driver: bridge
